spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/db-changelog.yaml
#  security:
#    user:
#      name: user
#      password: user

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE


